// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWCMOsyEwFEueLwexb3wiWub3kV2M8D2Q',
    appId: '1:389859678377:web:2c048c6c9659e6f40bb1b8',
    messagingSenderId: '389859678377',
    projectId: 'rusipe-app',
    authDomain: 'rusipe-app.firebaseapp.com',
    storageBucket: 'rusipe-app.appspot.com',
    measurementId: 'G-5H8TSJXE86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmg--bsBrRb7Sz_R95vMRGW1BWmOOkkkA',
    appId: '1:389859678377:android:e097b27f77c298b00bb1b8',
    messagingSenderId: '389859678377',
    projectId: 'rusipe-app',
    storageBucket: 'rusipe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA76DlnappRcST0gYaRtcyEMMz2SsoA_Ko',
    appId: '1:389859678377:ios:cda5c3d515e7730f0bb1b8',
    messagingSenderId: '389859678377',
    projectId: 'rusipe-app',
    storageBucket: 'rusipe-app.appspot.com',
    iosClientId: '389859678377-34db2dqg1e3ueik8hvmqmcd8b2a30r5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.rusipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA76DlnappRcST0gYaRtcyEMMz2SsoA_Ko',
    appId: '1:389859678377:ios:36f67922afe33ac00bb1b8',
    messagingSenderId: '389859678377',
    projectId: 'rusipe-app',
    storageBucket: 'rusipe-app.appspot.com',
    iosClientId: '389859678377-i635sb6akjbi1rp6g0oekdrh91ub2v3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.rusipeApp.RunnerTests',
  );
}
